### ISSUE TITLE
Access to UIBarButtonSystemItem Icons / Text

### ISSUE THREAD

**Issue by cancan101** [exponentjs/ex-navigator#28]
On IOS, the native navigator has access to the various icons and text in [`UIBarButtonSystemItem`](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIBarButtonItem_Class/#//apple_ref/c/tdef/UIBarButtonSystemItem). These icons are occasionally updated in new versions of IOS and the text is localized.

It would be great to have access tot these with ExNavigator on IOS.

**Comment by cancan101** [comment]
For example when using `UIBarButtonSystemItemCancel`:
![image](https://cloud.githubusercontent.com/assets/51059/11069034/3f2f5634-87a2-11e5-8623-656a66e3c1eb.png)
![image](https://cloud.githubusercontent.com/assets/51059/11069007/24cb1364-87a2-11e5-926d-7bb1cdd1cc37.png)
and I get this for "free" without having to do the localization of strings myself.

**Comment by jadsonlourenco** [comment]
@cancan101 I agree. But, I think the EX-Navigator is for "Router/Navigator" feature for RN. You can use a package like that: https://github.com/stefalda/ReactNativeLocalization for "language feature" - that can be used on all components - and use the **renderRightButton()** to render the text on Topbar.

```
import LocalizedStrings from 'react-native-localization';
let strings = new LocalizedStrings({
  en:{
    cancel: "Cancel",
  },
  pt: {
    cancel: "Cancelar",
  }
});
// Render
renderRightButton() {
  <Text>
    {strings.cancel}
  </Text>
}
```

**Comment by cancan101** [comment]
Sure, I was hoping to lean on the work Apple has already done to localize those strings rather than doing it myself (FWIW the linked library does look nice).

Further there is the question of getting access to the native icons. While there are packages like: https://github.com/corymsmith/react-native-icons and https://github.com/oblador/react-native-vector-icons, for consistency I would like to use the actual IOS native icons.

**Comment by ide** [comment]
One thing we're trying to do with ExNavigator is focus on cross-platform support. So we can take inspiration from Apple's design but can't rely on calling their actual functions. For example translating Cancel -> Cancelar is something you'll have to do however you see fit for your codebase. 

Likewise for the native icons we can't tell UINavigationController to display them because we're not using any complex UIKit views. My suggestion here would be to extract the iOS art assets and then display them using RN's `<Image>` component.

If there are generalized solutions for adding nav bar buttons that ExNavigator can help with, we can look into that.
