### ISSUE TITLE
Support better workflow for quick action scenerio

### ISSUE THREAD

**Issue by zackify** [exponentjs/ex-navigator#30]
I'm using [react native quick actions](https://github.com/jordanbyron/react-native-quick-actions) and I'm wondering if there is a better workflow than this. I'm trying to open a route when the user selects a route from a quick action menu. This has been the best I could come up with for replacing and going to a route, if the component has it in the stack, or just pushing it if it doesn't currently exist.

``` js
setTimeout(() => this.doQuickAction(QuickActions.popInitialAction()),100)
    this.subscription = React.DeviceEventEmitter.addListener('quickActionShortcut', this.doQuickAction);

....

let routes = this.props.navigator.getCurrentRoutes()

    if(data.userInfo.vaults){

      if(routes.length > 1){
        this.props.navigator.replaceAtIndex(MainRouter.getVaultsRoute({...data.userInfo}), 1)
        this.props.navigator.jumpTo(this.props.navigator.getCurrentRoutes()[1])
      }
      else this.props.navigator.push(MainRouter.getVaultsRoute({...data.userInfo}))
    }
    else if(data.userInfo.receipts){
      if(routes.length > 2){
        this.props.navigator.replaceAtIndex(MainRouter.getReceiptsRoute({...data.userInfo}), 2)
        this.props.navigator.jumpTo(this.props.navigator.getCurrentRoutes()[2])
      }
      else this.props.navigator.push(MainRouter.getReceiptsRoute({...data.userInfo}))
    }
```

Also, this is inside the initially loaded route, can't seem to find a better place to put this. I spent 30 minutes finding out I have to use a setTimeout or else the currentRoutes aren't set. Feels hacky, but actually works good. Any ideas? I'm sure this is going to be a valid use case for a lot of people in the near future. I thought of doing a pull request for adding `replaceAndGoTo` but wanted to post here first.

**Comment by ide** [comment]
It sounds like you want to take a URL -- that's effectively what a quick action is -- and navigate to it. Mobile is harder than web in this regard because as you've observed it's not as simple as navigating straight to the receipts screen in your example -- you care about the screens below it in the route stack. Also depending on how the user got to the URL, you want to transition differently -- if the user is launching the app via a shortcut from their home screen or a push notification, you want to immediately display the desired screen, while if they are navigating to the URL while your app is open, you want to transition to the new screen with an animation. All this is to say that routing is harder than it is on web and there isn't a generalized solution for this yet. My guess is it will take a good deal of experimentation and learning for a hypothetical react-native-router to get good (some discussion here: https://github.com/rackt/react-router/issues/743).

So... ExNavigator doesn't really focus on URL routing and we'd rather provide no abstraction than a bad abstraction. That's a theme of most of our APIs. But I have a couple of suggestions for how to structure your code that could make your codebase more pleasant to think about.

**Getting rid of the timeout**

The timeout is the wrong tool here since your intent is not to wait 100ms, but to wait until the navigator's route stack is set up, which happens to complete in under 100ms.... hopefully. Instead, I bet you could use componentDidMount to help with this.

``` js
class AppRoot extends React.Component {
  render() {
    return <ExNavigator ... />;
  }

  componentDidMount() {
    this.doQuickAction(QuickActions.popInitialAction());
    this.quickActionSub = ...
  }
}
```

Worst case, you may need to wrap `this.doQuickAction` in a `setImmediate` call to wait for the JS event loop to complete its tick but I doubt it.

**Initially rendering the initial action**

Rather than waiting for your app's root component to mount, you may want to immediately render the screen denoted by the Quick Action upon the initial render pass.

``` js
class AppRoot extends React.Component {
  constructor(props, context) {
    super(props, context);
    this.state = {
      // you could also store initialQuickAction but working with URLs allows you
      // to support LinkingIOS as well
      initialUrl: getUrlForQuickAction(QuickActions.popInitialAction());
    };
  }

  render() {
    return (
      <ExNavigator
        initialRouteStack={getRouteStackForUrl(this.state.initialUrl)}
      />
    );
  }
}
```

**Handling subsequent Quick Actions immediately**

When you get a Quick Action **after** the app has started you may want to immediately display the screen for that Quick Action when the app is foregrounded. Twitter does this with permalinks to tweets, for example. In this case you could use the method [`immediatelyResetRouteStack`](https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/Navigator/Navigator.js#L366).

``` js
class AppRoot extends React.Component {
  render() {
    return (
      <ExNavigator
        ref={navigator => { this._navigator = navigator; }}
      />
    );
  }

  componentDidMount() {
    this.doQuickAction(QuickActions.popInitialAction());
    this.quickActionSub = DeviceEventEmitter.addListener('quickActionShortcut', data => {
      let url = getUrlForQuickAction(data);  // or whatever the API is
      let routeStack = getRouteStackForUrl(url);
      this._navigator.immediatelyResetRouteStack(routeStack);
    });
  }
}
```

**Preserving UI state and reducing re-rendering when resetting the route stack**

One issue with resetting the route stack is that you might blow away UI state and incur extra rendering when resetting the route stack. Say your app has a Feed screen and a Tweet screen. If the user scrolls down Feed for a bit, leaves the app and taps a Quick Action that takes them to a Tweet, and then you reset the route stack to [Feed, Tweet], it might be nice to preserve their scroll position in the feed (not to mention it's slower to re-render a new Feed screen from scratch despite React's reconciliation efforts).

To achieve this I believe Navigator will re-use a scene component when you give it the exact same route object as before. So if your old route stack contains [Feed], and your new route stack contains [Feed', Tweet], it will see that `Feed !== Feed'` and render a new Feed scene. But if you re-use the same Feed route in the new route stack, Navigator will preserve the old Feed scene.

So when constructing the new route stack in response to a Quick Action, you may want to look at the current route stack:

``` js
// This method doesn't have to live inside of a component. You may very well want
// to put it in a helper module. Refactor as you see fit.
getRouteStackForUrl(url) {
  if (isHomeUrl(url)) {
    return [getHomeRoute()];
  }
  if (isTweetUrl(url)) {
    let tweetId = getTweetIdFromUrl(url);
    return [getHomeRoute(), getTweetRoute(tweetId)];
  }

  // This is the key function call that preserves UI state through route equality!
  // Think of it as implementing React's reconciliation, but for routes.
  reconcileRouteStacks(this._navigator.getCurrentRoutes(), newRouteStack);

  return newRouteStack;
}

reconcileRouteStacks(oldRouteStack, newRouteStack) {
  // Go through the old and new route stacks. If there are two routes in the same position in both
  // stacks that are logically equivalent (ex: you know they both represent the Feed screen) but
  // are different object instances, then use the copy the old route into the new route stack.
  // Implementation details left to the reader, partly because different people will have different ways
  // of writing this.
}
```

So, it should be possible to build all this on top of ExNavigator. We don't provide much out of the box though I could see a couple helper utils being useful as a separate npm package. At the end of this day if this seems hard or complex, that's partly because routing is hard on mobile (@brentvatne recently gave a talk on how users have higher expectations on mobile and how apps are very stateful -- here's the link in case you're interested: http://www.youtube.com/watch?v=9cIEtC-V2XE&t=5h44m00s). Hope this is helpful to you.

**Comment by zackify** [comment]
Thanks a ton for all of the help. I will try setImmediate because the
current routes are empty unless i had the timeout. Glad I'm not thinking
incorrectly and that this is actually hard to do.
